import media from '../content/moss-media.json' with {type:'json'};

const thresholds={common:[1,5,15,30],rare:[2,10,30,60],legendary:[3,15,45,90]};
const caps=value=>value[0].toUpperCase()+value.slice(1);

export function renderMossBody(project,projects,{escape:e,image}){
 const species=media.species;
 const first=species[0];
 const previewData=species.map(s=>({slug:s.slug,name:s.name,tier:s.tier,stages:s.stages,thresholds:thresholds[s.tier],habitat:s.habitat.src}));
 const pixel=(src,alt,size=64)=>`<img src="${e(src)}" width="${size}" height="${size}" alt="${e(alt)}" class="moss-pixel" loading="lazy" decoding="async">`;
 const sprite=first.stages[0].frames[0];
 const habitats=[...species,...media.legendaries];
 const index=projects.findIndex(p=>p.slug==='moss');
 return `<main id="main" class="moss-main">
 <div class="case-topline"><a href="/#work">← Back to collection</a><span>${String(index+1).padStart(2,'0')} / ${String(projects.length).padStart(2,'0')}</span></div>
 <section class="moss-hero" aria-labelledby="moss-title">
  <div class="moss-title-row"><div><p class="moss-kicker">A physical focus companion</p><h1 id="moss-title">Moss</h1></div><p class="moss-tagline">A little life<br>for your focus.</p></div>
  <figure class="moss-garden">${image(media.hero,{eager:true})}<figcaption>Farm redesign concept for phone. AI-generated concept art; the live farm is still being built toward it.</figcaption></figure>
  <div class="moss-introduction"><div><p class="moss-status"><span aria-hidden="true"></span>Working prototype · October 2026</p><p class="moss-contribution">Game design, pixel world, firmware &amp; web farm</p><a class="moss-link" href="https://moss.trevorcardozo.com">Visit the invite-only farm <span aria-hidden="true">↗</span></a></div><p class="moss-narrative">${e(project.summary)}</p></div>
  <nav class="moss-page-nav" aria-label="On this page"><a href="#moss-preview">Try the idea</a><a href="#moss-guide">Meet the companions</a><a href="#moss-notebook">Inside the build</a><a href="#moss-next">What’s growing next</a></nav>
 </section>
 <section class="moss-section moss-preview-section" id="moss-preview" aria-labelledby="moss-preview-title">
  <div class="moss-section-intro"><h2 id="moss-preview-title">Small sessions.<br>Slow growth.</h2><p>Pick a companion, mix its habitat artwork and look through its life. A completed 25-minute focus session adds one step toward its next evolution. There is no streak to lose, and no creature to punish when life gets busy.</p></div>
  <div class="moss-preview" data-moss-preview data-paused="true">
   <div class="moss-device-wrap"><div class="moss-device"><div class="moss-device-screen"><img class="moss-preview-habitat moss-pixel" data-preview-habitat src="${e(first.habitat.src)}" width="360" height="360" alt="" aria-hidden="true"><span class="moss-device-label" data-preview-name>${e(first.name)}</span><img class="moss-preview-sprite moss-pixel" data-preview-sprite src="${e(sprite)}" width="64" height="64" alt="${e(first.name)} Hatchling"><span class="moss-device-stage" data-preview-stage>Hatchling</span></div></div><p>Round-screen study · actual game sprites</p></div>
   <div class="moss-preview-controls"><div class="moss-enhancement" hidden><div class="moss-selects"><label>Companion species<select data-species aria-label="Companion species">${species.map((s,i)=>`<option value="${e(s.slug)}"${i===0?' selected':''}>${e(s.name)}</option>`).join('')}</select></label><label>Growth stage<select data-stage aria-label="Growth stage">${first.stages.map((s,i)=>`<option value="${i}">${e(s.name)}</option>`).join('')}</select></label><label class="moss-habitat-picker">Habitat artwork<select data-habitat aria-label="Habitat artwork">${habitats.map(s=>`<option value="${e(s.slug)}" data-src="${e(s.habitat.src)}">${e(s.name.replace(' spirit','').replace(' Legendary',''))}</option>`).join('')}</select></label></div><p class="moss-preview-status" data-preview-status role="status" aria-live="polite">1 completed session · Hatchling</p><div class="moss-growth-track" aria-hidden="true"><span data-growth-fill></span></div><p class="moss-next-stage" data-next-stage>4 more sessions to Youngster.</p><button type="button" class="moss-button" data-complete>Complete a preview session <span aria-hidden="true">+</span></button><div class="moss-small-controls"><button type="button" data-motion>Play sprite animation</button><button type="button" data-chime>Hear the three-note chime</button></div><p class="moss-audio-status" data-audio-status role="status"></p></div><p class="moss-noscript" data-preview-fallback>Enable JavaScript to try the local preview.</p><p class="moss-preview-note" data-preview-note>Illustrative preview. This runs only in your browser, skips the timer and does not connect to a device or save to the farm. Habitat mixing is an art study; collecting and applying backgrounds in the game is still planned. Audio plays only when you ask.</p></div>
  </div>
  <script type="application/json" id="moss-preview-data">${JSON.stringify(previewData).replaceAll('<','\\u003c')}</script>
 </section>
 <section class="moss-section" id="moss-guide" aria-labelledby="moss-guide-title">
  <div class="moss-section-intro"><h2 id="moss-guide-title">Five lives<br>in the woodland.</h2><div><p>The first family is already part of Moss. Each companion has its own silhouette and pace of growth, with habitat artwork to match. All five belong to the Woodland element.</p><p class="moss-small-note">Native game sprites with habitat artwork. Applying these backgrounds in the game is planned.</p></div></div>
  <div class="moss-field-guide" data-moss-field-guide>${species.map(s=>`<figure class="moss-species"><div class="moss-habitat-scene"><img src="${e(s.habitat.src)}" width="360" height="360" alt="${e(s.habitat.alt)}" loading="lazy" decoding="async" class="moss-pixel"><img src="${e(s.stages[3].frames[0])}" width="64" height="64" alt="${e(s.name)} in its Mature form" loading="lazy" decoding="async" class="moss-resident moss-pixel"></div><figcaption><div class="moss-species-heading"><h3>${e(s.name)}</h3><span>${e(caps(s.tier))}</span></div><p>${e(s.description)}</p><div class="moss-life-strip" aria-label="${e(s.name)} growth stages">${s.stages.map(stage=>`<div>${pixel(stage.frames[0],`${s.name} ${stage.name}`)}<span>${e(stage.name)}</span></div>`).join('')}</div></figcaption></figure>`).join('')}</div>
 </section>
 <section class="moss-section moss-notebook" id="moss-notebook" aria-labelledby="moss-notebook-title">
  <div class="moss-section-intro"><h2 id="moss-notebook-title">A tiny screen.<br>A real thing to build.</h2><p>Moss began with a simple question: could a focus timer give you something to care about? The round device holds one companion. The web farm gives the growing collection somewhere to live.</p></div>
  <div class="moss-device-evidence">${media.deviceViews.map(view=>`<figure>${image(view)}<figcaption>${e(view.caption)}</figcaption></figure>`).join('')}</div>
  <div class="moss-build-notes"><article><h3>On the desk</h3><p>A 360 × 360 round touch display on a Waveshare 1.85B board, powered by an ESP32-S3. One small, physical place to start a 25-minute session and see a companion grow.</p></article><article><h3>Time earns growth</h3><p>Focus runs locally on the device. Completed sessions earn evolution; interruptions don’t take growth away. Common, Rare and Legendary companions grow at different paces.</p></article><article><h3>A life that survives a restart</h3><p>Durable saves preserve the companion’s progress. The little world should be there when you return, even after the device has been switched off.</p></article><article><h3>One companion, one home</h3><p>The farm coordinates a one-way move from the device to the collection. A deposited companion stays on the farm, and the device begins again with a new egg. Creature packs are verified before the device accepts them.</p></article></div>
  <div class="moss-build-state"><p><strong>Where the build stands</strong> The physical device and invite-only web farm are running. Native sprites, focus screens, saved growth and the completion chime are in the prototype. Longer physical focus sessions and the full device-to-farm journey are still being tested.</p><a href="/work/trevos/">Related hardware: TrevOS <span aria-hidden="true">↗</span></a></div>
 </section>
 <section class="moss-section moss-future" id="moss-next" aria-labelledby="moss-next-title">
  <div class="moss-section-intro"><h2 id="moss-next-title">Beyond<br>the woodland.</h2><div><p>Seven new elemental Legendaries are taking shape: Fire, Water, Electric, Ghost, Earth, Air and Space. A wider, more colourful world, with a different character in every corner.</p><p class="moss-art-status">Art ready · Game integration still ahead</p></div></div>
  <div class="moss-legendaries" data-moss-legendaries>${media.legendaries.map(s=>`<figure class="moss-legendary" style="--element-color:${e(s.color)}"><div class="moss-legendary-art"><img src="${e(s.habitat.src)}" width="360" height="360" alt="${e(s.habitat.alt)}" loading="lazy" decoding="async" class="moss-pixel"><img src="${e(s.forms[3].src)}" width="64" height="64" alt="${e(s.name)} Mature artwork" loading="lazy" decoding="async" class="moss-legendary-resident moss-pixel"></div><figcaption><span class="moss-element">${e(s.element)}</span><h3>${e(s.name)}</h3><div class="moss-future-forms" aria-label="${e(s.name)} artwork across four growth stages">${s.forms.map(f=>pixel(f.src,`${s.name} ${f.name}`)).join('')}</div></figcaption></figure>`).join('')}</div>
  <p class="moss-future-note">These are the real creature and habitat assets for the next family. They are not yet available as playable species in the device or farm. The artwork was generated with AI and prepared as native pixel game art.</p>
  <div class="moss-closing"><p>Something small.<br>Worth coming back to.</p><a class="moss-link" href="/#work">Back to the collection <span aria-hidden="true">↗</span></a></div>
 </section>
 </main>`;
}
