export const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escape;
const arrow = '<span aria-hidden="true">↗</span>';
export const image = (m, {eager=false, cover=false}={}) => `<img src="${e(m.src)}" ${m.variants?.length ? `srcset="${m.variants.map(v=>`${e(v.src)} ${v.width}w`).join(', ')}" sizes="${cover?'(max-width: 699px) 90vw, (max-width: 1099px) 44vw, 36vw':'(max-width: 699px) 92vw, 80vw'}"` : ''} width="${m.width}" height="${m.height}" alt="${e(m.alt)}" loading="${eager?'eager':'lazy'}" decoding="async" ${eager?'fetchpriority="high"':''}>`;
const links = items => items.map(l=>`<a href="${e(l.href)}">${e(l.label)} ${arrow}</a>`).join('');
const header = `<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="signature" href="/" aria-label="Trevor Cardozo home">Trevor Cardozo<span class="signature-dot" aria-hidden="true">[tc]</span></a><nav aria-label="Main"><a href="/#work">Work <span aria-hidden="true">↓</span></a><a href="/#about">About</a><a href="mailto:trevor.cardozo@gmail.com">Say hello ${arrow}</a></nav></header>`;
const footer = `<footer id="about" class="site-footer"><div><span class="eyebrow">A little about me</span><h2>Made for<br>real life.</h2></div><div class="footer-note"><p>I'm Trevor, an educator based in Bangkok. My work moves between the classroom, the workbench and the screen: learning with children, building tools for school life, and making things for friends and the games we play.</p><p>If something here connects with what you're making, <a href="mailto:trevor.cardozo@gmail.com">say hello ${arrow}</a>.</p><div class="elsewhere">${links([{label:'LinkedIn',href:'https://www.linkedin.com/in/tcardozo/'},{label:'Substack',href:'https://trevorcardozo.substack.com/'},{label:'GitHub',href:'https://github.com/Tr3v0r86'}])}</div></div><div class="colophon"><span>Trevor Cardozo © ${new Date().getUTCFullYear()}</span><span>Always something in the making.</span><a href="#top">Back to top ↑</a></div></footer>`;
function document({title, description, path, cover, body, kind='home'}){
 return `<!doctype html><html lang="en" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f3ec"><title>${e(title)}</title><meta name="description" content="${e(description)}"><link rel="canonical" href="https://trevorcardozo.com${path}"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="https://trevorcardozo.com${path}">${cover?`<meta property="og:image" content="https://trevorcardozo.com${e(cover.src)}"><meta property="og:image:alt" content="${e(cover.alt)}">`:''}<meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/fonts/display.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/fonts/body.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/styles.css"><script src="/assets/collection.js" defer></script></head><body class="${kind}">${header}${body}${footer}</body></html>`;
}
export function renderHome(projects){
 const cards=projects.filter(p=>p.featured).map((p,i)=>`<article class="piece piece--${e(p.slug)}"><a class="piece-link" href="/work/${e(p.slug)}/" data-project="${e(p.slug)}" aria-describedby="desc-${e(p.slug)}"><div class="artifact">${image(p.cover,{eager:i<2,cover:true})}<span class="piece-open" aria-hidden="true">↗</span></div><div class="piece-caption"><span class="index">${String(i+1).padStart(2,'0')}</span><div><h3>${e(p.title)}</h3><p id="desc-${e(p.slug)}">${e(p.descriptor)}</p><span class="project-status">${e(p.status)}</span></div><span class="caption-arrow" aria-hidden="true">↗</span></div></a><template data-preview="${e(p.slug)}"><span data-title>${e(p.title)}</span><span data-status>${e(p.status)}</span><span data-summary>${e(p.summary.split(/(?<=\.)\s/)[0])}</span><span data-number>${String(i+1).padStart(2,'0')}</span></template></article>`).join('');
 return document({title:'Trevor Cardozo — Educator, maker, designer', description:'I make tools, objects and places that help people learn, play and make things.',path:'/',cover:projects[0].cover,body:`<main id="main"><section class="intro" aria-labelledby="identity"><div class="intro-kicker"><span class="eyebrow">A practice in making</span><span class="location">Bangkok, Thailand</span></div><h1 id="identity">Professional educator.<br><span>Hobbyist maker.</span><br>Amateur designer.</h1><div class="intro-bottom"><p>I make tools, objects and places that help people<br class="desktop-break"> learn, play and make things.</p><a href="#work" class="work-jump">Explore the collection <span aria-hidden="true">↓</span></a></div></section><section id="work" aria-labelledby="work-title" class="work-section"><div class="section-label"><h2 id="work-title">The collection</h2><span>${String(projects.filter(p=>p.featured).length).padStart(2,'0')} pieces · An open notebook</span></div><div class="collection-layout"><div class="collection">${cards}</div><aside class="preview" aria-label="Selected project preview"><div class="preview-inner"><span class="preview-marker" aria-hidden="true" data-preview-number>—</span><span class="eyebrow" data-preview-status>A closer look</span><h3 data-preview-title>Choose a piece<br>to explore.</h3><p data-preview-summary>From a classroom investigation to a printed character case. Each project has a different reason to exist.</p><span class="preview-hint">Open any piece ↗</span></div></aside></div></section></main>`});
}
function figure(m,i){return `<figure class="gallery-item gallery-item--${e(m.layout||'wide')}"><div class="gallery-image">${image(m)}</div><figcaption><span class="figure-number">${String(i+2).padStart(2,'0')}</span><span>${e(m.caption||m.alt)}${m.credit?`<span class="credit">${m.credit.url?`<a href="${e(m.credit.url)}">${e(m.credit.text)}</a>`:e(m.credit.text)}</span>`:''}</span></figcaption>${m.textEquivalent?`<details class="image-description"><summary>Image description</summary><p>${e(m.textEquivalent)}</p></details>`:''}${m.accessibleLink?links([m.accessibleLink]):''}</figure>`;}
export function renderCase(p,projects){const i=projects.findIndex(x=>x.slug===p.slug);return document({title:`${p.title} — Trevor Cardozo`,description:p.summary,path:`/work/${p.slug}/`,cover:p.cover,kind:`case case--${p.slug} ${p.cover.height>p.cover.width?'case--portrait':'case--landscape'}`,body:`<main id="main"><div class="case-topline"><a href="/#work">← Back to collection</a><span>${String(i+1).padStart(2,'0')} / ${String(projects.length).padStart(2,'0')}</span></div><header class="case-heading"><p class="eyebrow">${e(p.descriptor)}</p><h1>${e(p.title)}</h1><dl class="case-meta"><div><dt>Contribution</dt><dd>${e(p.role)}</dd></div><div><dt>Status</dt><dd>${e(p.status)}</dd></div>${p.dateLabel?`<div><dt>When</dt><dd>${e(p.dateLabel)}</dd></div>`:''}</dl></header><section class="case-lead" aria-label="About the project"><figure class="case-hero"><div class="hero-image">${image(p.cover,{eager:true})}</div><figcaption><span>01</span><span>${e(p.cover.caption||p.cover.alt)}${p.cover.credit?`<span class="credit">${p.cover.credit.url?`<a href="${e(p.cover.credit.url)}">${e(p.cover.credit.text)}</a>`:e(p.cover.credit.text)}</span>`:''}</span></figcaption>${p.cover.textEquivalent?`<details class="image-description"><summary>Image description</summary><p>${e(p.cover.textEquivalent)}</p></details>`:''}${p.cover.accessibleLink?links([p.cover.accessibleLink]):''}</figure><div class="case-story"><p>${e(p.summary)}</p><div class="project-links">${links(p.links||[])}</div></div></section><section class="case-gallery" aria-label="Project images"><div class="gallery-heading"><h2>A closer look</h2><span>${p.gallery.length} ${p.gallery.length===1?'view':'views'} · From the project</span></div>${p.gallery.map(figure).join('')}</section><nav class="case-pagination" aria-label="More work">${i>0?`<a href="/work/${e(projects[i-1].slug)}/"><span>← Previous piece</span><strong>${e(projects[i-1].title)}</strong></a>`:'<span></span>'}${i<projects.length-1?`<a href="/work/${e(projects[i+1].slug)}/"><span>Next piece →</span><strong>${e(projects[i+1].title)}</strong></a>`:'<a href="/#work"><span>Back to collection ↑</span><strong>Keep exploring</strong></a>'}</nav></main>`});}
export const render404=()=>document({title:'Piece not found — Trevor Cardozo',description:'Return to the collection.',path:'/404.html',body:'<main id="main" class="not-found"><p class="eyebrow">404 · A loose end</p><h1>This piece<br>isn’t here.</h1><a href="/#work">Back to the collection ↗</a></main>'});
