import {projectIcon,socialIcon} from './icons.mjs';
import {renderMossBody} from './moss-page.mjs';
import about from '../content/about.json' with {type:'json'};
import {searchMetadata} from './seo.mjs';
export const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escape;
const arrow = '<span aria-hidden="true">↗</span>';
export const image = (m, {eager=false, cover=false}={}) => `<img src="${e(m.src)}" ${m.variants?.length ? `srcset="${m.variants.map(v=>`${e(v.src)} ${v.width}w`).join(', ')}" sizes="${cover?'(max-width: 699px) 82vw, 56vw':'(max-width: 699px) 92vw, 80vw'}"` : ''} width="${m.width}" height="${m.height}" alt="${e(m.alt)}" loading="${eager?'eager':'lazy'}" decoding="async" ${eager?'fetchpriority="high"':''}>`;
const links = items => items.map(l=>`<a href="${e(l.href)}">${socialIcon(l.href)}${e(l.label)} ${arrow}</a>`).join('');
const header = `<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="signature" href="/" aria-label="Trevor Cardozo home">Trevor Cardozo<span class="signature-dot" aria-hidden="true">[tc]</span></a><nav aria-label="Main"><a href="/#work">Work <span aria-hidden="true">↓</span></a><a href="/about/">About</a><a href="mailto:trevor.cardozo@gmail.com">Say hello ${arrow}</a></nav></header>`;
const footer = `<footer id="about" class="site-footer"><div><span class="eyebrow">A little about me</span><h2>Made for<br>real life.</h2></div><div class="footer-note"><p>I'm Trevor Cardozo, based in Bangkok. My training is in alternative education; my professional work is in school operations. Making and design connect the two, from the conditions children need to create to the systems families and school teams use every day. Away from school, I make things for friends, games and everyday life.</p><p>If something here connects with what you're making, <a href="mailto:trevor.cardozo@gmail.com">say hello ${arrow}</a>.</p><p><a href="/about/">More about me ↗</a></p><div class="elsewhere">${links([{label:'LinkedIn',href:'https://www.linkedin.com/in/tcardozo/'},{label:'Substack',href:'https://trevorcardozo.substack.com/'},{label:'GitHub',href:'https://github.com/Tr3v0r86'}])}</div></div><div class="colophon"><span>Trevor Cardozo © ${new Date().getUTCFullYear()}</span><span>Always something in the making.</span><a href="#top">Back to top ↑</a></div></footer>`;
function document({title, description, path, cover, body, kind='home', styles=[], scripts=[]}){
 const seo=searchMetadata({title,description,path,cover});title=seo.title;description=seo.description;
 return `<!doctype html><html lang="en" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f3ec"><title>${e(title)}</title><meta name="description" content="${e(description)}"><meta name="robots" content="${seo.robots}"><meta name="author" content="Trevor Cardozo">${seo.jsonLd?`<script type="application/ld+json">${seo.jsonLd}</script>`:''}<link rel="canonical" href="https://trevorcardozo.com${path}"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="https://trevorcardozo.com${path}">${cover?`<meta property="og:image" content="https://trevorcardozo.com${e(cover.src)}"><meta property="og:image:alt" content="${e(cover.alt)}">`:''}<meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.png" type="image/png" sizes="32x32"><link rel="icon" href="/favicon.svg" type="image/svg+xml" sizes="any"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="preload" href="/fonts/schibsted-grotesk.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/styles.css"><script src="/assets/collection.js" defer></script>${styles.map(file=>`<link rel="stylesheet" href="/assets/${e(file)}">`).join('')}${scripts.map(file=>`<script src="/assets/${e(file)}" defer></script>`).join('')}</head><body class="${kind}">${header}${body}${footer}</body></html>`;
}
// Collection cards: photos crop to the 8:9 holding frame, screens sit whole on a tint. The first four load eagerly.
const eagerCards=4;
const coverImage=(m,i)=>`<img src="${e(m.src)}"${m.variants?.length?` srcset="${m.variants.map(v=>`${e(v.src)} ${v.width}w`).join(', ')}" sizes="(max-width:820px) 78vw, 27vw"`:''} width="${m.width}" height="${m.height}" alt="${e(m.alt)}" loading="${i<eagerCards?'eager':'lazy'}" decoding="async"${i===0?' fetchpriority="high"':''} draggable="false">`;
// Random project order per visit, applied before first paint and held in sessionStorage so returning to the collection keeps it. /?order=catalog keeps catalog order (tests, review).
const shuffle='<script>(()=>{if(new URLSearchParams(location.search).get("order")==="catalog")return;const track=document.querySelector(".collection"),slides=[...track.children],options=[...document.querySelectorAll(".project-picker option")],n=slides.length,slug=s=>s.querySelector("[data-project]").dataset.project,key="collection-order";let saved;try{saved=JSON.parse(sessionStorage.getItem(key));}catch{}const bySlug=new Map(slides.map(s=>[slug(s),s]));if(Array.isArray(saved)&&saved.length===n&&saved.every(x=>bySlug.has(x))&&new Set(saved).size===n)slides.splice(0,n,...saved.map(x=>bySlug.get(x)));else{for(let i=n-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[slides[i],slides[j]]=[slides[j],slides[i]];}try{sessionStorage.setItem(key,JSON.stringify(slides.map(slug)));}catch{}}slides.forEach((slide,i)=>{const title=slide.querySelector("h3").textContent,num=String(i+1).padStart(2,"0");track.append(slide);slide.querySelector(".index").textContent=num;options[i].textContent=num+" · "+title;slide.querySelectorAll(".artifact img").forEach(img=>{img.loading=i<'+eagerCards+'?"eager":"lazy";if(i===0)img.fetchPriority="high";else img.removeAttribute("fetchpriority");});});})();</script>';
export function renderHome(projects){
 const featured=projects.filter(p=>p.featured),count=String(featured.length).padStart(2,'0'),pad=i=>String(i+1).padStart(2,'0');
 const cards=featured.map((p,i)=>{const screen=p.collectionFrame==='screen';return `<li class="piece piece--${e(p.slug)}"><a class="piece-link" href="/work/${e(p.slug)}/" data-project="${e(p.slug)}"><div class="artifact ${screen?`artifact--screen tint-${e(p.collectionTint)}`:'artifact--photo'}">${coverImage(p.collectionCover??p.cover,i)}<span class="artifact-open" aria-hidden="true">↗</span></div><div class="piece-caption"><h3>${e(p.title)}</h3><span class="index" aria-hidden="true">${pad(i)}</span><p>${e(p.descriptor)}</p><span class="project-status">${e(p.status)}</span></div></a></li>`;}).join('');
 const intro=`<section class="intro" aria-labelledby="identity"><div class="intro-kicker"><span class="eyebrow">A practice in making</span><span class="location">Bangkok, Thailand</span></div><h1 id="identity"><span>Trained alternative educator.</span> <span>Professional school operator.</span> <span>Hobbyist maker.</span> <span>Amateur designer.</span></h1><div class="intro-bottom"><p>I make tools, objects and places that help people learn, play and make things.</p></div></section>`;
 const work=`<section class="work-section" id="work" aria-labelledby="work-title"><div class="section-label"><h2 id="work-title">A working collection.</h2><div class="carousel-controls"><div data-carousel-count aria-live="polite">01<span> / ${count}</span></div><div class="carousel-navigation"><button type="button" data-prev aria-label="Previous project">←</button><button type="button" data-next aria-label="Next project">→</button></div></div></div><ol class="collection" tabindex="0" aria-label="Projects, scroll sideways">${cards}</ol><div class="collection-foot"><label class="project-picker">Jump to a project<select>${featured.map((p,i)=>`<option value="${i}">${pad(i)} · ${e(p.title)}</option>`).join('')}</select></label><div class="carousel-progress" aria-hidden="true"><i></i></div></div>${shuffle}</section>`;
 return document({title:'Trevor Cardozo — Alternative educator, school operator, maker and designer', description:'I make tools, objects and places that help people learn, play and make things.',path:'/',cover:projects[0].collectionCover||projects[0].cover,body:`<main id="main">${intro}${work}</main>`});
}
const video = m => `<video src="${e(m.src)}" poster="${e(m.poster)}" width="${m.width}" height="${m.height}" aria-label="${e(m.alt)}" controls muted loop playsinline preload="metadata"></video>`;
function figure(m,i){return `<figure class="gallery-item gallery-item--${e(m.layout||'wide')}"><div class="gallery-image">${m.poster?video(m):image(m)}</div><figcaption><span class="figure-number">${String(i+2).padStart(2,'0')}</span><span>${e(m.caption||m.alt)}${m.credit?`<span class="credit">${m.credit.url?`<a href="${e(m.credit.url)}">${e(m.credit.text)}</a>`:e(m.credit.text)}</span>`:''}</span></figcaption>${m.textEquivalent?`<details class="image-description"><summary>Image description</summary><p>${e(m.textEquivalent)}</p></details>`:''}${m.accessibleLink?links([m.accessibleLink]):''}</figure>`;}
export function renderCase(p,projects){if(p.slug==='moss')return document({title:'Moss — Trevor Cardozo',description:p.summary,path:'/work/moss/',cover:p.cover,kind:'case case--moss',styles:['moss.css'],scripts:['moss.js'],body:renderMossBody(p,projects,{escape:e,image})});const i=projects.findIndex(x=>x.slug===p.slug);return document({title:`${p.title} — Trevor Cardozo`,description:p.summary,path:`/work/${p.slug}/`,cover:p.cover,kind:`case case--${p.slug} ${p.cover.height>p.cover.width?'case--portrait':'case--landscape'}`,body:`<main id="main"><div class="case-topline"><a href="/#work">← Back to collection</a><span>${String(i+1).padStart(2,'0')} / ${String(projects.length).padStart(2,'0')}</span></div><header class="case-heading"><p class="eyebrow case-icon-label">${projectIcon(p.slug)}<span>${e(p.descriptor)}</span></p><h1>${e(p.title)}</h1><dl class="case-meta"><div><dt>Contribution</dt><dd>${e(p.role)}</dd></div><div><dt>Status</dt><dd>${e(p.status)}</dd></div>${p.dateLabel?`<div><dt>When</dt><dd>${e(p.dateLabel)}</dd></div>`:''}</dl></header><section class="case-lead" aria-label="About the project"><figure class="case-hero"><div class="hero-image">${image(p.cover,{eager:true})}</div><figcaption><span>01</span><span>${e(p.cover.caption||p.cover.alt)}${p.cover.credit?`<span class="credit">${p.cover.credit.url?`<a href="${e(p.cover.credit.url)}">${e(p.cover.credit.text)}</a>`:e(p.cover.credit.text)}</span>`:''}</span></figcaption>${p.cover.textEquivalent?`<details class="image-description"><summary>Image description</summary><p>${e(p.cover.textEquivalent)}</p></details>`:''}${p.cover.accessibleLink?links([p.cover.accessibleLink]):''}</figure><div class="case-story"><p>${e(p.summary)}</p><div class="project-links">${links(p.links||[])}</div></div></section><section class="case-gallery" aria-label="Project images"><div class="gallery-heading"><h2>A closer look</h2><span>${p.gallery.length} ${p.gallery.length===1?'view':'views'} · From the project</span></div>${p.gallery.map(figure).join('')}</section><nav class="case-pagination" aria-label="More work">${i>0?`<a href="/work/${e(projects[i-1].slug)}/"><span>← Previous piece</span><strong>${e(projects[i-1].title)}</strong></a>`:'<span></span>'}${i<projects.length-1?`<a href="/work/${e(projects[i+1].slug)}/"><span>Next piece →</span><strong>${e(projects[i+1].title)}</strong></a>`:'<a href="/#work"><span>Back to collection ↑</span><strong>Keep exploring</strong></a>'}</nav></main>`});}
export const render404=()=>document({title:'Piece not found — Trevor Cardozo',description:'Return to the collection.',path:'/404.html',body:'<main id="main" class="not-found"><p class="eyebrow">404 · A loose end</p><h1>This piece<br>isn’t here.</h1><a href="/#work">Back to the collection ↗</a></main>'});

export function renderAbout(){return document({title:'About Trevor Cardozo | Education, School Operations & Making',description:'Trevor Cardozo is a trained alternative educator, professional school operator, hobbyist maker and amateur designer based in Bangkok.',path:'/about/',cover:about.portrait,kind:'about',body:`<main id="main"><section class="about-layout" aria-labelledby="about-title"><figure class="about-portrait">${image(about.portrait,{eager:true})}<figcaption>${e(about.portrait.caption)}</figcaption></figure><div class="about-story"><p class="eyebrow">Bangkok, Thailand</p><h1 id="about-title">A little<br>about me.</h1><p>I work in education and school operations in Bangkok. For 15 years, I've been involved in Reggio-inspired projects with children and colleagues. My day-to-day work also includes looking after school spaces, helping families find what they need and making tools for school teams.</p><p>Outside school, I tinker with electronics, make things for tabletop games and build small apps for friends. This site brings those projects together, including the ones I'm still figuring out.</p><a class="work-jump" href="/#work">Back to the projects <span aria-hidden="true">↗</span></a></div></section></main>`});}
